import 'package:flutter_gyw/flutter_gyw.dart';
import 'package:freezed_annotation/freezed_annotation.dart';
// ignore: unused_import
import 'package:flutter/foundation.dart';

// required: associates our `slides.dart` with the code generated by Freezed
part 'slides.freezed.dart';
// optional: Since our Slides class is serializable, we must add this line.
// But if Slides was not serializable, we could skip it.
part 'slides.g.dart';

@freezed
class Slides with _$Slides {
  const factory Slides({
    required String name,
    required List<GYWDrawing> drawings,
  }) = _Slides;

  factory Slides.fromJson(Map<String, Object?> json)
      => _$SlidesFromJson(json);
}